"""DDIC field descriptions and the alias catalogue of the migration cockpit templates.

`FIELD_DESCRIPTIONS` holds the short description of every field in the table catalog as the SAP data dictionary
shows it (data element short text). The template-driven cockpit export uses them to recognise a template field by
its *description* when its technical name is not the DDIC name (migration object templates and BAPIs use their own
names).

`TEMPLATE_ALIASES` maps such names to DDIC field names. The entries come from the public BAPI interface
structures the migration objects are built on (BAPIACHE09/BAPIACGL09/BAPIACAR09/BAPIACAP09/BAPIACCR09 for
accounting documents, BAPI2017_GM_* for goods movements, BAPIMEPOHEADER/BAPIMEPOITEM for purchase orders,
BAPISDHD1/BAPISDITM for sales orders, BAPIOBDLVHDRCHG/BAPIOBDLVITEMCHG for deliveries, BAPI1022_* for assets,
BAPI0012_*/BAPI0015_* for cost and profit centers, BAPIMATHEAD/BAPI_MARA/BAPI_MARC/BAPI_MBEW for products,
BAPI customer/vendor master structures) and from field names seen in migration object field lists. They are
heuristics: the mapping report labels every alias so it can be checked against the template's Field List
description, and `propose_aliases` learns project-specific ones from a registered template's Field List.
"""
from __future__ import annotations

FIELD_DESCRIPTIONS: dict[str, str] = {
    "ARBID": "Work Center Object ID",
    "ARBPL": "Work Center",
    "BMEIN": "Base Unit of Measure (BOM)",
    "BMENG": "Base Quantity",
    "BMSCH": "Base Quantity (Operation)",
    "CHARG": "Batch Number",
    "CINSM": "Batch Stock in Quality Inspection",
    "CLABS": "Unrestricted Batch Stock",
    "CSPEM": "Blocked Batch Stock",
    "DATUV": "Valid-From Date",
    "ENDDA": "Valid-To Date",
    "ERSDA": "Created On",
    "HSDAT": "Date of Manufacture",
    "IDNRK": "BOM Component",
    "LASET": "Cost Center Assignment Counter",
    "LICHA": "Vendor Batch Number",
    "LOSBS": "To Lot Size",
    "LOSVN": "From Lot Size",
    "LTXA1": "Operation Short Text",
    "OBJID": "Object ID (Work Center)",
    "OBJTY": "Object Type (Work Center)",
    "PLNAL": "Group Counter",
    "PLNKN": "Task List Node Number",
    "PLNME": "Task List Unit of Measure",
    "PLNNR": "Task List Group",
    "PLNTY": "Task List Type",
    "POSTP": "Item Category (BOM)",
    "STATU": "Task List Status",
    "STEUS": "Control Key",
    "STLAL": "Alternative BOM",
    "STLAN": "BOM Usage",
    "STLKN": "BOM Item Node Number",
    "STLNR": "Bill of Material",
    "STLST": "BOM Status",
    "STLTY": "BOM Category",
    "VERWE": "Usage (Task List / Work Center)",
    "VFDAT": "Shelf Life Expiration Date",
    "VGE01": "Unit of Standard Value 1",
    "VGW01": "Standard Value 1 (Setup)",
    "VGWTS": "Standard Value Key",
    "VORNR": "Operation Number",
    "AFABE": "Depreciation Area",
    "AKONT": "Reconciliation Account in General Ledger",
    "AKTIV": "Asset Capitalization Date",
    "ANLKL": "Asset Class",
    "ANLN1": "Main Asset Number",
    "ANBWA": "Asset Transaction Type",
    "AWITEM": "Reference Document Item",
    "AWREF": "Reference Document",
    "BWASL": "Asset Transaction Type",
    "BZDAT": "Asset Value Date",
    "DOCLN": "Six-Character Posting Item for Ledger",
    "DRCRK": "Debit/Credit Indicator",
    "HSL": "Amount in Company Code Currency",
    "KSL": "Amount in Global Currency",
    "LDGRP": "Ledger Group",
    "MOVCAT": "Movement Category",
    "OSL": "Amount in Freely Defined Currency 1",
    "POPER": "Posting Period",
    "TABNAME": "Table Name",
    "TABCLASS": "Table Category",
    "SQLTAB": "Name of the SQL Table",
    "ROLLNAME": "Data Element",
    "POSITION": "Position of the Field in the Table",
    "LENG": "Length",
    "KEYFLAG": "Identifies a Key Field of a Table",
    "FIELDNAME": "Field Name",
    "DEVCLASS": "Package",
    "DDTEXT": "Short Description of Repository Objects",
    "DDLANGUAGE": "Language Key",
    "DATATYPE": "Data Type in ABAP Dictionary",
    "CONTFLAG": "Delivery Class",
    "AS4VERS": "Version of the Entry",
    "AS4LOCAL": "Activation Status of a Repository Object",
    "PEINH": "Price Unit",
    "PVPRS": "Periodic Unit Price",
    "SALKV": "Value Based on Moving Average Price",
    "CURTP": "Currency Type",
    "UNTPER": "Posting Subperiod",
    "BDATJ": "Posting Date Year",
    "KALNR": "Cost Estimate Number",
    "RACCT": "Account Number",
    "RASSC": "Company ID of Trading Partner",
    "RBUKRS": "Company Code",
    "RCNTR": "Cost Center",
    "RHCUR": "Company Code Currency",
    "RLDNR": "Ledger in General Ledger Accounting",
    "RWCUR": "Transaction Currency",
    "SLALITTYPE": "Subledger-Specific Line Item Type",
    "SUBTA": "Partial Document Number",
    "WSL": "Amount in Transaction Currency",
    "ANLN2": "Asset Subnumber",
    "AUART": "Order Type",
    "AUBEL": "Sales Document",
    "AUDAT": "Document Date",
    "AUFNR": "Order Number",
    "AUGBL": "Clearing Document",
    "AUGDT": "Clearing Date",
    "AUPOS": "Sales Document Item",
    "AWKEY": "Reference Key",
    "AWTYP": "Reference Transaction",
    "BEDAT": "Purchase Order Date",
    "BELNR": "Document Number",
    "BESKZ": "Procurement Type",
    "BEWTP": "Purchase Order History Category",
    "BEZEI": "Description",
    "BLART": "Document Type",
    "BLDAT": "Document Date",
    "BSART": "Purchasing Document Type",
    "BSTAT": "Document Status",
    "BSTYP": "Purchasing Document Category",
    "BUDAT": "Posting Date",
    "BUKRS": "Company Code",
    "BUKRS_VF": "Company Code to Be Billed",
    "BUTXT": "Company Code Name",
    "BUZEI": "Line Item",
    "BVORG": "Cross-Company Code Posting Number",
    "BWART": "Movement Type",
    "BWKEY": "Valuation Area",
    "BWTAR": "Valuation Type",
    "CONTROLLED": "Export Controlled",
    "DATBI": "Valid To",
    "DISPO": "MRP Controller",
    "DMBTR": "Amount in Local Currency",
    "DWERK": "Delivering Plant",
    "EBELN": "Purchasing Document Number",
    "EBELP": "Purchasing Document Item",
    "ECCN": "Export Control Classification Number",
    "EKGRP": "Purchasing Group",
    "EKORG": "Purchasing Organization",
    "EKOTX": "Purchasing Organization Description",
    "ELIKZ": "Delivery Completed Indicator",
    "END_DATE": "End Date",
    "ESG_SCORE": "ESG Score",
    "FKART": "Billing Type",
    "FKDAT": "Billing Date",
    "FKIMG": "Billed Quantity",
    "GAMNG": "Total Order Quantity",
    "GBSTK": "Overall Processing Status",
    "GJAHR": "Fiscal Year",
    "GLTRP": "Basic Finish Date",
    "GSTRP": "Basic Start Date",
    "GVTYP": "P&L Statement Account Type",
    "HKONT": "General Ledger Account",
    "ISM01": "Activity Quantity",
    "JOBCOUNT": "Job ID",
    "JOBNAME": "Job Name",
    "KANSW": "Cumulative Acquisition Value",
    "KNAFA": "Cumulative Depreciation",
    "KOART": "Account Type",
    "KOKRS": "Controlling Area",
    "KOSTL": "Cost Center",
    "KTEXT": "Short Text",
    "KTOKD": "Customer Account Group",
    "KTOKK": "Vendor Account Group",
    "KTOPL": "Chart of Accounts",
    "KTPLT": "Chart of Accounts Description",
    "KUNNR": "Customer",
    "KUNRG": "Payer",
    "KWMENG": "Order Quantity",
    "LABST": "Unrestricted-Use Stock",
    "LAND1": "Country Key",
    "LBKUM": "Total Valuated Stock",
    "LFART": "Delivery Type",
    "LFIMG": "Delivery Quantity",
    "LGORT": "Storage Location",
    "LICENSE_REQ": "License Required",
    "LIFNR": "Supplier",
    "LMNGA": "Yield",
    "LOGSYS": "Logical System",
    "MAKTX": "Material Description",
    "MANDT": "Client",
    "MATKL": "Material Group",
    "MATNR": "Material",
    "MBLNR": "Material Document",
    "MEINS": "Base Unit of Measure",
    "MENGE": "Quantity",
    "MESTYP": "Message Type",
    "MITKZ": "Reconciliation Account Type",
    "MJAHR": "Material Document Year",
    "MONAT": "Fiscal Period",
    "MTART": "Material Type",
    "MTEXT": "Client Description",
    "NAFAG": "Ordinary Depreciation Posted",
    "NAME1": "Name",
    "NETPR": "Net Price",
    "NETWR": "Net Value",
    "PARNUM": "Partner Number",
    "PARTYP": "Partner Type",
    "PERIODIC": "Periodic Job",
    "PERIV": "Fiscal Year Variant",
    "PLNBEZ": "Material Number",
    "POSNN": "Subsequent Document Item",
    "POSNR": "Item",
    "POSNV": "Preceding Document Item",
    "PRCTR": "Profit Center",
    "PSMNG": "Order Item Quantity",
    "RBSTAT": "Invoice Document Status",
    "RCVPOR": "Receiver Port",
    "RFBSK": "Status for Transfer to Accounting",
    "RFCDEST": "RFC Destination",
    "RFCHOST": "RFC Host",
    "RFCOPTIONS": "RFC Options",
    "RFCTYPE": "RFC Type",
    "RFMNG": "Referenced Quantity",
    "RISK_RATING": "Risk Rating",
    "RMWWR": "Gross Invoice Amount",
    "RMZHL": "Confirmation Counter",
    "RUECK": "Confirmation Number",
    "SAKNR": "G/L Account",
    "SALK3": "Total Value",
    "SDLUNAME": "Scheduler User",
    "SERVICE": "Service",
    "SHKZG": "Debit/Credit Indicator",
    "SPART": "Division",
    "SPRAS": "Language Key",
    "STATUS": "Status",
    "STPRS": "Standard Price",
    "TCODE2": "Transaction Code",
    "TSA_ID": "TSA Identifier",
    "TXT50": "Long Text",
    "UMSKS": "Special G/L Transaction Type",
    "UMSKZ": "Special G/L Indicator",
    "UMWRK": "Receiving Plant",
    "VBELN": "Sales Document",
    "VBELV": "Preceding Document",
    "VBTYP_N": "Subsequent Document Category",
    "VBTYP_V": "Preceding Document Category",
    "VBUND": "Trading Partner",
    "VERPR": "Moving Average Price",
    "VGABE": "Transaction/Event Type",
    "VGBEL": "Reference Document",
    "VGPOS": "Reference Item",
    "VKORG": "Sales Organization",
    "VPRSV": "Price Control",
    "VSTEL": "Shipping Point",
    "VTEXT": "Description",
    "VTWEG": "Distribution Channel",
    "WADAT_IST": "Actual Goods Movement Date",
    "WAERK": "Document Currency",
    "WAERS": "Currency",
    "WEMNG": "Goods Receipt Quantity",
    "KDATB": "Start of Validity Period",
    "KDATE": "End of Validity Period",
    "KTWRT": "Target Value of the Outline Agreement",
    "KONNR": "Number of Principal Purchase Agreement (Contract)",
    "KTPNR": "Item Number of Principal Purchase Agreement",
    "LOEKZ": "Deletion Indicator in Purchasing Document",
    "ETENR": "Delivery Schedule Line Counter",
    "EINDT": "Item Delivery Date",
    "WERKS": "Plant",
    "WRBTR": "Amount in Document Currency",
    "XBILK": "Balance Sheet Account",
    "XBLNR": "Reference Document Number",
    "XOPVW": "Open Item Management",
    "ZEILE": "Material Document Item",
    "ZEKKN": "Sequential Number of Account Assignment",
    "ZTERM": "Payment Terms",
    "ZUONR": "Assignment",
}

# migration template / BAPI field name -> DDIC field name
TEMPLATE_ALIASES: dict[str, str] = {
    # organisation and general
    "COMP_CODE": "BUKRS", "COMPANYCODE": "BUKRS", "COMPANY_CODE": "BUKRS", "CC": "BUKRS",
    "COMP_CODE_NAME": "BUTXT", "COMPANY_NAME": "BUTXT",
    "CHRT_ACCTS": "KTOPL", "CHARTOFACCOUNTS": "KTOPL", "CHART_OF_ACCOUNTS": "KTOPL", "COA": "KTOPL",
    "CO_AREA": "KOKRS", "CONTROLLINGAREA": "KOKRS", "CONTROLLING_AREA": "KOKRS", "CONTROLAREA": "KOKRS",
    "COSTCENTER": "KOSTL", "COST_CENTER": "KOSTL", "COSTCTR": "KOSTL",
    "PROFIT_CTR": "PRCTR", "PROFITCENTER": "PRCTR", "PROFIT_CENTER": "PRCTR",
    "FISC_YEAR": "GJAHR", "FISCALYEAR": "GJAHR", "FISCAL_YEAR": "GJAHR", "FISCYEAR": "GJAHR",
    "FIS_PERIOD": "MONAT", "FISCAL_PERIOD": "MONAT", "FISCALPERIOD": "MONAT", "PERIOD": "MONAT",
    "FISC_VARIANT": "PERIV", "FISCALYEARVARIANT": "PERIV",
    "CURRENCY": "WAERS", "CURR": "WAERS", "CURRENCYCODE": "WAERS", "CURRENCY_ISO": "WAERS", "DOC_CURR": "WAERS",
    "COUNTRY": "LAND1", "COUNTRYKEY": "LAND1", "COUNTRY_KEY": "LAND1",
    "LANGU": "SPRAS", "LANGUAGE": "SPRAS", "LANGUAGEKEY": "SPRAS",
    "PLANT": "WERKS", "PLANTID": "WERKS",
    "STGE_LOC": "LGORT", "STORAGELOCATION": "LGORT", "STORAGE_LOCATION": "LGORT", "STLOC": "LGORT",
    "VAL_AREA": "BWKEY", "VALUATIONAREA": "BWKEY", "VALUATION_AREA": "BWKEY",
    "VAL_TYPE": "BWTAR", "VALUATIONTYPE": "BWTAR", "VALUATION_TYPE": "BWTAR",
    "SALESORG": "VKORG", "SALES_ORG": "VKORG", "SALESORGANIZATION": "VKORG", "SALES_ORGANIZATION": "VKORG",
    "DISTR_CHAN": "VTWEG", "DISTRIBUTIONCHANNEL": "VTWEG", "DISTRIBUTION_CHANNEL": "VTWEG", "DIST_CHANNEL": "VTWEG",
    "DIVISION": "SPART", "ORGANIZATIONDIVISION": "SPART",
    "PURCH_ORG": "EKORG", "PURCHASINGORGANIZATION": "EKORG", "PURCHASING_ORGANIZATION": "EKORG", "PURORG": "EKORG",
    "PUR_GROUP": "EKGRP", "PURCHASINGGROUP": "EKGRP", "PURCHASING_GROUP": "EKGRP", "PURGROUP": "EKGRP",
    "SHIP_POINT": "VSTEL", "SHIPPINGPOINT": "VSTEL", "SHIPPING_POINT": "VSTEL",
    "TRADE_ID": "VBUND", "TRADINGPARTNER": "VBUND", "TRADING_PARTNER": "VBUND", "PARTNER_COMPANY": "VBUND",
    "LOGICALSYSTEM": "LOGSYS", "LOGICAL_SYSTEM": "LOGSYS",
    "CLIENT": "MANDT",
    # business partners
    "CUSTOMER": "KUNNR", "CUSTOMERNO": "KUNNR", "CUSTOMER_NO": "KUNNR", "CUSTOMERNUMBER": "KUNNR", "KUNNR_RG": "KUNRG",
    "SOLD_TO": "KUNNR", "SOLDTO": "KUNNR", "SOLDTOPARTY": "KUNNR", "SOLD_TO_PARTY": "KUNNR",
    "PAYER": "KUNRG", "PAYERPARTY": "KUNRG", "PAYER_PARTY": "KUNRG",
    "SUPPLIER": "LIFNR", "VENDOR": "LIFNR", "VENDOR_NO": "LIFNR", "VENDORNO": "LIFNR", "SUPPLIERNUMBER": "LIFNR", "CREDITOR": "LIFNR",
    "ACCOUNT_GROUP": "KTOKD", "ACCT_GROUP_CUSTOMER": "KTOKD", "ACCT_GROUP_VENDOR": "KTOKK",
    "NAME": "NAME1", "NAME_1": "NAME1", "ORGANIZATIONNAME1": "NAME1", "ORGANIZATION_NAME_1": "NAME1",
    "RECON_ACCT": "AKONT", "RECONCILIATIONACCOUNT": "AKONT", "RECONCILIATION_ACCOUNT": "AKONT", "RECON_ACCOUNT": "AKONT",
    "PMNTTRMS": "ZTERM", "PAYMENTTERMS": "ZTERM", "PAYMENT_TERMS": "ZTERM", "PMNT_TERMS": "ZTERM", "TERMS_OF_PAYMENT": "ZTERM",
    # G/L accounts
    "GL_ACCOUNT": "SAKNR", "GLACCOUNT": "SAKNR", "GL_ACCT": "SAKNR", "ACCOUNT": "SAKNR", "G_L_ACCOUNT": "SAKNR",
    "BAL_SHEET": "XBILK", "BALANCESHEETACCOUNT": "XBILK", "BALANCE_SHEET_ACCOUNT": "XBILK", "BAL_SHEET_ACCT": "XBILK",
    "PL_STATEMENT": "GVTYP", "PL_STMT_TYPE": "GVTYP", "PLACCOUNTTYPE": "GVTYP", "P_L_STATEMENT_TYPE": "GVTYP",
    "RECON_ACCT_TYPE": "MITKZ", "RECONCILIATIONACCOUNTTYPE": "MITKZ", "RECONACCTTYPE": "MITKZ",
    "OPEN_ITEM": "XOPVW", "OPEN_ITEM_MGT": "XOPVW", "OPENITEMMANAGEMENT": "XOPVW", "OPEN_ITEM_MANAGEMENT": "XOPVW", "OI_MGMT": "XOPVW",
    "DESCRIPT": "TXT50", "LONG_TEXT": "TXT50", "LONGTEXT": "TXT50", "GLACCOUNTLONGNAME": "TXT50", "ACCOUNT_LONG_TEXT": "TXT50",
    "SHORT_TEXT": "KTEXT", "SHORTTEXT": "KTEXT", "DESCRIPTION": "KTEXT", "TEXT": "KTEXT", "NAME_TEXT": "KTEXT",
    "VALID_TO": "DATBI", "VALIDTO": "DATBI", "VALIDITYENDDATE": "DATBI", "DATE_TO": "DATBI",
    # accounting documents (BAPIACHE09 / BAPIACGL09 / BAPIACAR09 / BAPIACAP09 / BAPIACCR09)
    "DOC_DATE": "BLDAT", "DOCUMENTDATE": "BLDAT", "DOCUMENT_DATE": "BLDAT",
    "PSTNG_DATE": "BUDAT", "POSTINGDATE": "BUDAT", "POSTING_DATE": "BUDAT", "POST_DATE": "BUDAT",
    "DOC_TYPE": "BLART", "DOCUMENTTYPE": "BLART", "DOCUMENT_TYPE": "BLART", "ACCOUNTINGDOCUMENTTYPE": "BLART",
    "DOC_NO": "BELNR", "DOCUMENTNUMBER": "BELNR", "DOCUMENT_NUMBER": "BELNR", "ACC_DOC_NO": "BELNR", "ACCOUNTINGDOCUMENT": "BELNR", "OBJ_KEY": "AWKEY",
    "REF_DOC_NO": "XBLNR", "REFERENCE": "XBLNR", "REFERENCEDOCUMENT": "XBLNR", "REF_DOC": "XBLNR", "DOCUMENTREFERENCEID": "XBLNR",
    "ITEMNO_ACC": "BUZEI", "LINE_ITEM": "BUZEI", "LINEITEM": "BUZEI", "ITEM_NO": "BUZEI",
    "GL_ACCOUNT_ITEM": "HKONT", "GLACCOUNT_ITEM": "HKONT", "GENERALLEDGERACCOUNT": "HKONT",
    "AMT_DOCCUR": "WRBTR", "AMOUNT_DOC_CURR": "WRBTR", "AMOUNTINTRANSACTIONCURRENCY": "WRBTR", "AMOUNT": "WRBTR", "DOC_AMOUNT": "WRBTR",
    "AMT_LOCCUR": "DMBTR", "AMOUNT_LOC_CURR": "DMBTR", "AMOUNTINCOMPANYCODECURRENCY": "DMBTR", "LOCAL_AMOUNT": "DMBTR",
    "DE_CRE_IND": "SHKZG", "DEBITCREDITCODE": "SHKZG", "DEBIT_CREDIT": "SHKZG", "DR_CR": "SHKZG", "DC_IND": "SHKZG",
    "ALLOC_NMBR": "ZUONR", "ASSIGNMENT": "ZUONR", "ASSIGNMENTREFERENCE": "ZUONR", "ALLOCATION": "ZUONR",
    "SP_GL_IND": "UMSKZ", "SPECIALGLCODE": "UMSKZ", "SPECIAL_GL_INDICATOR": "UMSKZ", "SPGL_IND": "UMSKZ",
    "SP_GL_TYPE": "UMSKS", "SPECIALGLTRANSACTIONTYPE": "UMSKS",
    "CLEAR_DOC": "AUGBL", "CLEARINGDOCUMENT": "AUGBL", "CLEARING_DOCUMENT": "AUGBL",
    "CLEAR_DATE": "AUGDT", "CLEARINGDATE": "AUGDT", "CLEARING_DATE": "AUGDT",
    "ACCT_TYPE": "KOART", "ACCOUNTTYPE": "KOART", "ACCOUNT_TYPE": "KOART",
    "REF_KEY": "AWKEY", "REFERENCEKEY": "AWKEY", "AWREF": "AWKEY", "REF_TRANS": "AWTYP", "REFERENCETRANSACTION": "AWTYP",
    "DOC_STATUS": "BSTAT", "DOCUMENTSTATUS": "BSTAT", "CROSS_CC_NO": "BVORG", "CROSSCOMPANYPOSTING": "BVORG",
    # products / materials (BAPIMATHEAD, BAPI_MARA, BAPI_MARC, BAPI_MBEW, BAPI_MARD)
    "MATERIAL": "MATNR", "MATERIAL_LONG": "MATNR", "PRODUCT": "MATNR", "MATERIALNUMBER": "MATNR", "MATERIAL_NUMBER": "MATNR", "MATNR_EXTERNAL": "MATNR",
    "MATL_DESC": "MAKTX", "MATERIALDESCRIPTION": "MAKTX", "MATERIAL_DESCRIPTION": "MAKTX", "PRODUCTDESCRIPTION": "MAKTX", "MAT_DESC": "MAKTX",
    "MATL_TYPE": "MTART", "MATERIALTYPE": "MTART", "MATERIAL_TYPE": "MTART", "PRODUCTTYPE": "MTART",
    "MATL_GROUP": "MATKL", "MATERIALGROUP": "MATKL", "MATERIAL_GROUP": "MATKL", "PRODUCTGROUP": "MATKL",
    "BASE_UOM": "MEINS", "BASEUNIT": "MEINS", "BASE_UNIT": "MEINS", "BASE_UNIT_OF_MEASURE": "MEINS", "UNIT_OF_MEASURE": "MEINS", "UOM": "MEINS",
    "PROC_TYPE": "BESKZ", "PROCUREMENTTYPE": "BESKZ", "PROCUREMENT_TYPE": "BESKZ",
    "MRP_CTRLER": "DISPO", "MRPCONTROLLER": "DISPO", "MRP_CONTROLLER": "DISPO",
    "PRICE_CTRL": "VPRSV", "PRICECONTROL": "VPRSV", "PRICE_CONTROL": "VPRSV",
    "STD_PRICE": "STPRS", "STANDARDPRICE": "STPRS", "STANDARD_PRICE": "STPRS",
    "MOVING_PR": "VERPR", "MOVINGAVERAGEPRICE": "VERPR", "MOVING_AVERAGE_PRICE": "VERPR", "MAP": "VERPR",
    "TOTAL_STOCK": "LBKUM", "TOTALVALUATEDSTOCK": "LBKUM", "VALUATED_STOCK": "LBKUM",
    "TOTAL_VALUE": "SALK3", "TOTALVALUE": "SALK3", "STOCK_VALUE": "SALK3",
    "UNRESTRICTED_STOCK": "LABST", "UNRESTRICTEDSTOCK": "LABST", "STOCK_QTY": "LABST", "UNRESTRICTED_USE_STOCK": "LABST",
    # goods movements (BAPI2017_GM_HEAD_01 / BAPI2017_GM_ITEM_CREATE)
    "MAT_DOC": "MBLNR", "MATERIALDOCUMENT": "MBLNR", "MATERIAL_DOCUMENT": "MBLNR",
    "DOC_YEAR": "MJAHR", "MATERIALDOCUMENTYEAR": "MJAHR", "MAT_DOC_YEAR": "MJAHR",
    "MOVE_TYPE": "BWART", "MOVEMENTTYPE": "BWART", "MOVEMENT_TYPE": "BWART", "GOODSMOVEMENTTYPE": "BWART",
    "ENTRY_QNT": "MENGE", "QUANTITY": "MENGE", "QUANTITYINENTRYUNIT": "MENGE", "QTY": "MENGE", "ENTRY_QUANTITY": "MENGE",
    "MATDOC_ITM": "ZEILE", "MATERIALDOCUMENTITEM": "ZEILE", "MAT_DOC_ITEM": "ZEILE",
    "MOVE_PLANT": "UMWRK", "RECEIVINGPLANT": "UMWRK", "RECEIVING_PLANT": "UMWRK",
    "ORDERID": "AUFNR", "ORDER_ID": "AUFNR", "ORDER_NO": "AUFNR", "ORDERNUMBER": "AUFNR", "MANUFACTURINGORDER": "AUFNR", "PROD_ORDER": "AUFNR",
    "TRANSACTION_CODE": "TCODE2", "TCODE": "TCODE2",
    # purchasing (BAPIMEPOHEADER / BAPIMEPOITEM / BAPIEKBE)
    "PO_NUMBER": "EBELN", "PURCH_ORD": "EBELN", "PURCHASEORDER": "EBELN", "PURCHASE_ORDER": "EBELN", "PO_NO": "EBELN", "PURCHASINGDOCUMENT": "EBELN",
    "PO_ITEM": "EBELP", "PURCHASEORDERITEM": "EBELP", "PURCHASE_ORDER_ITEM": "EBELP", "PO_ITM": "EBELP", "PURCHASINGDOCUMENTITEM": "EBELP",
    "PO_DATE": "BEDAT", "PURCHASEORDERDATE": "BEDAT", "PURCHASE_ORDER_DATE": "BEDAT", "CREAT_DATE": "BEDAT",
    "DOC_CAT": "BSTYP", "PURCHASINGDOCUMENTCATEGORY": "BSTYP", "PO_CATEGORY": "BSTYP",
    "PO_TYPE": "BSART", "DOCTYPE": "BSART", "PURCHASEORDERTYPE": "BSART", "PURCHASINGDOCUMENTTYPE": "BSART", "ORDER_TYPE_PO": "BSART",
    "NET_PRICE": "NETPR", "NETPRICE": "NETPR", "NETPRICEAMOUNT": "NETPR", "PRICE": "NETPR",
    "NO_MORE_GR": "ELIKZ", "DELIVERY_COMPLETED": "ELIKZ", "ISCOMPLETELYDELIVERED": "ELIKZ", "DEL_COMPL": "ELIKZ",
    "HIST_TYPE": "BEWTP", "PO_HISTORY_CATEGORY": "BEWTP", "PURCHASINGHISTORYCATEGORY": "BEWTP",
    "SERIAL_NO": "ZEKKN", "ACCOUNT_ASSIGNMENT_NO": "ZEKKN", "ACCASSIGNMENTNUMBER": "ZEKKN",
    "EVENT_TYPE": "VGABE", "TRANSACTION_TYPE": "VGABE", "PROCESS_TYPE": "VGABE",
    # sales and distribution (BAPISDHD1 / BAPISDITM / BAPIOBDLV* / billing)
    "SALES_DOC": "VBELN", "SALESDOCUMENT": "VBELN", "SALES_DOCUMENT": "VBELN", "SALESORDER": "VBELN", "SALES_ORDER": "VBELN", "SD_DOC": "VBELN",
    "DELIV_NUMB": "VBELN", "DELIVERYDOCUMENT": "VBELN", "DELIVERY_DOCUMENT": "VBELN", "DELIVERY": "VBELN", "DELIVERY_NO": "VBELN",
    "BILL_DOC": "VBELN", "BILLINGDOCUMENT": "VBELN", "BILLING_DOCUMENT": "VBELN", "INVOICE_NO": "VBELN", "BILLING_DOC": "VBELN",
    "ITM_NUMBER": "POSNR", "ITEM": "POSNR", "ITEM_NUMBER": "POSNR", "SALESDOCUMENTITEM": "POSNR", "DELIV_ITEM": "POSNR", "DELIVERYDOCUMENTITEM": "POSNR", "BILLINGDOCUMENTITEM": "POSNR", "BILL_ITEM": "POSNR",
    "DOC_TYPE_SD": "AUART", "SALESDOCUMENTTYPE": "AUART", "SALES_DOCUMENT_TYPE": "AUART", "ORDER_TYPE": "AUART", "ORDERTYPE": "AUART",
    "REQ_QTY": "KWMENG", "ORDERQUANTITY": "KWMENG", "ORDER_QUANTITY": "KWMENG", "REQUESTEDQUANTITY": "KWMENG", "TARGET_QTY": "KWMENG",
    "DLV_QTY": "LFIMG", "DELIVERYQUANTITY": "LFIMG", "DELIVERY_QUANTITY": "LFIMG", "ACTUALDELIVERYQUANTITY": "LFIMG", "DELIV_QTY": "LFIMG",
    "BILL_QTY": "FKIMG", "BILLEDQUANTITY": "FKIMG", "BILLED_QUANTITY": "FKIMG", "BILLINGQUANTITY": "FKIMG", "INV_QTY": "FKIMG",
    "NET_VALUE": "NETWR", "NETVALUE": "NETWR", "NET_VAL": "NETWR", "NETAMOUNT": "NETWR", "NET_AMOUNT": "NETWR", "TOTALNETAMOUNT": "NETWR", "NET_VAL_HD": "NETWR", "NET_VAL_ITEM": "NETWR",
    "BILL_TYPE": "FKART", "BILLINGDOCUMENTTYPE": "FKART", "BILLING_TYPE": "FKART",
    "BILL_DATE": "FKDAT", "BILLINGDOCUMENTDATE": "FKDAT", "BILLING_DATE": "FKDAT",
    "DLV_TYPE": "LFART", "DELIVERYDOCUMENTTYPE": "LFART", "DELIVERY_TYPE": "LFART",
    "GI_DATE": "WADAT_IST", "ACTUALGOODSMOVEMENTDATE": "WADAT_IST", "ACTUAL_GI_DATE": "WADAT_IST", "GOODS_ISSUE_DATE": "WADAT_IST",
    "DOC_CURRENCY": "WAERK", "TRANSACTIONCURRENCY": "WAERK", "SD_CURRENCY": "WAERK", "DOCUMENTCURRENCY": "WAERK",
    "REF_DOC_SD": "VGBEL", "REFERENCESDDOCUMENT": "VGBEL", "REFERENCE_DOCUMENT": "VGBEL", "PRECEDING_DOCUMENT": "VGBEL",
    "REF_DOC_IT": "VGPOS", "REFERENCESDDOCUMENTITEM": "VGPOS", "REFERENCE_ITEM": "VGPOS", "PRECEDING_ITEM": "VGPOS",
    "ORDER_REF": "AUBEL", "SALESORDERREF": "AUBEL", "ORDER_ITEM_REF": "AUPOS",
    "ACCOUNTING_STATUS": "RFBSK", "POSTING_STATUS": "RFBSK", "ACCOUNTINGTRANSFERSTATUS": "RFBSK",
    "OVERALL_STATUS": "GBSTK", "OVERALLSDPROCESSSTATUS": "GBSTK", "PROCESSING_STATUS": "GBSTK",
    "CC_BILLING": "BUKRS_VF", "COMPANYCODEBILLING": "BUKRS_VF", "BILLING_COMPANY_CODE": "BUKRS_VF",
    "PURCH_DATE": "AUDAT", "ORDER_DATE": "AUDAT", "SALESDOCUMENTDATE": "AUDAT",
    # assets (BAPI1022_*)
    "ASSET": "ANLN1", "ASSETMAINNO": "ANLN1", "MAIN_ASSET_NUMBER": "ANLN1", "MASTERFIXEDASSET": "ANLN1", "ASSET_NO": "ANLN1",
    "SUBNUMBER": "ANLN2", "ASSETSUBNO": "ANLN2", "ASSET_SUBNUMBER": "ANLN2", "FIXEDASSET": "ANLN2", "SUB_NUMBER": "ANLN2",
    "ASSETCLASS": "ANLKL", "ASSET_CLASS": "ANLKL",
    "CAP_DATE": "AKTIV", "CAPITALIZATIONDATE": "AKTIV", "CAPITALIZATION_DATE": "AKTIV", "ASSETCAPITALIZATIONDATE": "AKTIV",
    "DESCRIPT_ASSET": "TXT50", "ASSET_DESCRIPTION": "TXT50", "FIXEDASSETDESCRIPTION": "TXT50",
    "AREA": "AFABE", "DEPR_AREA": "AFABE", "DEPRECIATIONAREA": "AFABE", "DEPRECIATION_AREA": "AFABE",
    "ACQ_VALUE": "KANSW", "ACQUISITIONVALUE": "KANSW", "ACQUISITION_VALUE": "KANSW", "APC": "KANSW", "CUM_ACQ_VALUE": "KANSW",
    "ACC_DEPREC": "KNAFA", "ACCUMULATEDDEPRECIATION": "KNAFA", "ACCUMULATED_DEPRECIATION": "KNAFA", "CUM_DEPR": "KNAFA",
    "ORD_DEP": "NAFAG", "ORDINARYDEPRECIATION": "NAFAG", "ORDINARY_DEPRECIATION": "NAFAG", "DEPR_POSTED": "NAFAG",
    # production (BAPI_PRODORD_*)
    "PRODUCTIONORDER": "AUFNR", "PRODUCTION_ORDER": "AUFNR", "MANUFACTURINGORDERITEM": "POSNR", "ORDER_ITEM": "POSNR",
    "TOTAL_QTY": "GAMNG", "TOTALQUANTITY": "GAMNG", "ORDER_QTY": "GAMNG", "MFGORDERPLANNEDTOTALQTY": "GAMNG",
    "ITEM_QTY": "PSMNG", "ORDERITEMQUANTITY": "PSMNG", "PLANNED_QTY": "PSMNG",
    "GR_QTY": "WEMNG", "GOODSRECEIPTQUANTITY": "WEMNG", "GOODS_RECEIPT_QUANTITY": "WEMNG", "DELIVERED_QTY": "WEMNG",
    "BASIC_START": "GSTRP", "BASICSTARTDATE": "GSTRP", "BASIC_START_DATE": "GSTRP", "MFGORDERSCHEDULEDSTARTDATE": "GSTRP",
    "BASIC_FINISH": "GLTRP", "BASICFINISHDATE": "GLTRP", "BASIC_FINISH_DATE": "GLTRP", "MFGORDERSCHEDULEDENDDATE": "GLTRP",
    "PROD_PLANT": "DWERK", "PRODUCTIONPLANT": "DWERK", "PRODUCTION_PLANT": "DWERK", "DELIVERING_PLANT": "DWERK",
    "CONF_NO": "RUECK", "CONFIRMATIONNUMBER": "RUECK", "CONFIRMATION_NUMBER": "RUECK", "CONFIRMATION": "RUECK",
    "CONF_CNT": "RMZHL", "CONFIRMATIONCOUNTER": "RMZHL", "CONFIRMATION_COUNTER": "RMZHL",
    "YIELD": "LMNGA", "CONFIRMEDYIELDQUANTITY": "LMNGA", "YIELD_QTY": "LMNGA", "CONFIRMED_QUANTITY": "LMNGA",
    "ACT_QTY": "ISM01", "ACTIVITYQUANTITY": "ISM01", "ACTIVITY_QUANTITY": "ISM01",
    "MATERIAL_HEADER": "PLNBEZ", "ORDER_MATERIAL": "PLNBEZ",
    # supplier invoices (BAPI_INCINV_*)
    "INV_DOC_NO": "BELNR", "SUPPLIERINVOICE": "BELNR", "SUPPLIER_INVOICE": "BELNR", "INVOICE_DOC": "BELNR",
    "GROSS_AMOUNT": "RMWWR", "GROSSAMOUNT": "RMWWR", "INVOICEGROSSAMOUNT": "RMWWR", "GROSS_INV_AMOUNT": "RMWWR",
    "INV_STATUS": "RBSTAT", "INVOICESTATUS": "RBSTAT", "INVOICE_STATUS": "RBSTAT",
    "INV_ITEM": "BUZEI", "SUPPLIERINVOICEITEM": "BUZEI", "INVOICE_ITEM": "BUZEI",
    "ITEM_AMOUNT": "WRBTR", "SUPPLIERINVOICEITEMAMOUNT": "WRBTR",
    # custom tables of the demo landscape
    "EXPORT_CONTROLLED": "CONTROLLED", "ECCN_CODE": "ECCN", "LICENSE_REQUIRED": "LICENSE_REQ", "TSA": "TSA_ID", "SERVICE_ID": "SERVICE", "VALID_UNTIL": "END_DATE",
}
