"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 05:15:20.815742
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_subject_id'), ['subject_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agent_decisions',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_decisions_project_id'), ['project_id'], unique=False)

    op.create_table('rule_sets',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_yaml', sa.Text(), nullable=False),
    sa.Column('compiled', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'version', name='uq_ruleset_version')
    )
    with op.batch_alter_table('rule_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_sets_project_id'), ['project_id'], unique=False)

    op.create_table('sap_systems',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.String(length=8), nullable=False),
    sa.Column('client', sa.String(length=3), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('release', sa.String(length=32), nullable=False),
    sa.Column('database', sa.String(length=32), nullable=False),
    sa.Column('os_name', sa.String(length=32), nullable=False),
    sa.Column('connector', sa.String(length=32), nullable=False),
    sa.Column('connector_status', sa.String(length=32), nullable=False),
    sa.Column('logical_system', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sap_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sap_systems_project_id'), ['project_id'], unique=False)

    op.create_table('scope_manifests',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('selection', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'version', name='uq_manifest_version')
    )
    with op.batch_alter_table('scope_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_manifests_project_id'), ['project_id'], unique=False)

    op.create_table('business_object_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=48), nullable=False),
    sa.Column('object_key', sa.String(length=120), nullable=False),
    sa.Column('bukrs', sa.String(length=4), nullable=True),
    sa.Column('werks', sa.String(length=4), nullable=True),
    sa.Column('gjahr', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('company_codes', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'object_type', 'object_key', name='uq_bo_instance')
    )
    with op.batch_alter_table('business_object_instances', schema=None) as batch_op:
        batch_op.create_index('ix_bo_sys_type', ['system_id', 'object_type'], unique=False)
        batch_op.create_index('ix_bo_sys_type_bukrs', ['system_id', 'object_type', 'bukrs'], unique=False)

    op.create_table('discovery_snapshots',
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_snapshots_system_id'), ['system_id'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('from_node', sa.String(length=160), nullable=False),
    sa.Column('to_node', sa.String(length=160), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index('ix_ge_sys_from', ['system_id', 'from_node'], unique=False)
        batch_op.create_index('ix_ge_sys_to', ['system_id', 'to_node'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=160), nullable=False),
    sa.Column('node_type', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'node_id', name='uq_graph_node')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_gn_sys_type', ['system_id', 'node_type'], unique=False)

    op.create_table('migration_runs',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('manifest_id', sa.String(length=32), nullable=False),
    sa.Column('ruleset_id', sa.String(length=32), nullable=False),
    sa.Column('source_system_id', sa.String(length=32), nullable=False),
    sa.Column('target_system_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['scope_manifests.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rule_sets.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['sap_systems.id'], ),
    sa.ForeignKeyConstraint(['target_system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_migration_runs_project_id'), ['project_id'], unique=False)

    op.create_table('org_units',
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('unit_type', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_type', sa.String(length=32), nullable=True),
    sa.Column('parent_code', sa.String(length=10), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_units_system_id'), ['system_id'], unique=False)

    op.create_table('sap_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('table_name', sa.String(length=30), nullable=False),
    sa.Column('record_key', sa.String(length=200), nullable=False),
    sa.Column('bukrs', sa.String(length=4), nullable=True),
    sa.Column('werks', sa.String(length=4), nullable=True),
    sa.Column('gjahr', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'table_name', 'record_key', name='uq_sap_record')
    )
    with op.batch_alter_table('sap_records', schema=None) as batch_op:
        batch_op.create_index('ix_sap_records_sys_table', ['system_id', 'table_name'], unique=False)
        batch_op.create_index('ix_sap_records_sys_table_bukrs', ['system_id', 'table_name', 'bukrs'], unique=False)

    op.create_table('reconciliation_results',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('check_name', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('source_value', sa.String(length=120), nullable=False),
    sa.Column('target_value', sa.String(length=120), nullable=False),
    sa.Column('variance', sa.String(length=120), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_results_run_id'), ['run_id'], unique=False)

    op.create_table('run_stages',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_stages_run_id'), ['run_id'], unique=False)

    op.create_table('staged_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('partition', sa.String(length=64), nullable=False),
    sa.Column('table_name', sa.String(length=30), nullable=False),
    sa.Column('record_key', sa.String(length=200), nullable=False),
    sa.Column('source_payload', sa.JSON(), nullable=False),
    sa.Column('target_payload', sa.JSON(), nullable=True),
    sa.Column('target_key', sa.String(length=200), nullable=True),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('load_status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'table_name', 'record_key', name='uq_staged')
    )
    with op.batch_alter_table('staged_records', schema=None) as batch_op:
        batch_op.create_index('ix_staged_run_table', ['run_id', 'table_name'], unique=False)

    op.create_table('table_statistics',
    sa.Column('system_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('table_name', sa.String(length=30), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('est_bytes', sa.Integer(), nullable=False),
    sa.Column('by_company_code', sa.JSON(), nullable=False),
    sa.Column('by_fiscal_year', sa.JSON(), nullable=False),
    sa.Column('key_fields', sa.JSON(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['discovery_snapshots.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['sap_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_statistics_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_statistics_system_id'), ['system_id'], unique=False)

    op.create_table('transformation_exceptions',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('table_name', sa.String(length=30), nullable=False),
    sa.Column('record_key', sa.String(length=200), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transformation_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transformation_exceptions_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transformation_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transformation_exceptions_run_id'))

    op.drop_table('transformation_exceptions')
    with op.batch_alter_table('table_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_statistics_system_id'))
        batch_op.drop_index(batch_op.f('ix_table_statistics_snapshot_id'))

    op.drop_table('table_statistics')
    with op.batch_alter_table('staged_records', schema=None) as batch_op:
        batch_op.drop_index('ix_staged_run_table')

    op.drop_table('staged_records')
    with op.batch_alter_table('run_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_stages_run_id'))

    op.drop_table('run_stages')
    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_run_id'))

    op.drop_table('reconciliation_results')
    with op.batch_alter_table('sap_records', schema=None) as batch_op:
        batch_op.drop_index('ix_sap_records_sys_table_bukrs')
        batch_op.drop_index('ix_sap_records_sys_table')

    op.drop_table('sap_records')
    with op.batch_alter_table('org_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_units_system_id'))

    op.drop_table('org_units')
    with op.batch_alter_table('migration_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_runs_project_id'))

    op.drop_table('migration_runs')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_gn_sys_type')

    op.drop_table('graph_nodes')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_ge_sys_to')
        batch_op.drop_index('ix_ge_sys_from')

    op.drop_table('graph_edges')
    with op.batch_alter_table('discovery_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_snapshots_system_id'))

    op.drop_table('discovery_snapshots')
    with op.batch_alter_table('business_object_instances', schema=None) as batch_op:
        batch_op.drop_index('ix_bo_sys_type_bukrs')
        batch_op.drop_index('ix_bo_sys_type')

    op.drop_table('business_object_instances')
    with op.batch_alter_table('scope_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_manifests_project_id'))

    op.drop_table('scope_manifests')
    with op.batch_alter_table('sap_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sap_systems_project_id'))

    op.drop_table('sap_systems')
    with op.batch_alter_table('rule_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_sets_project_id'))

    op.drop_table('rule_sets')
    with op.batch_alter_table('agent_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_decisions_project_id'))

    op.drop_table('agent_decisions')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('audit_events')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_subject_id'))

    op.drop_table('approvals')
    # ### end Alembic commands ###
