"""extraction jobs

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-09 13:31:05.890890
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_jobs',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('partition_id', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=48), nullable=False),
    sa.Column('est_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['migration_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'partition_id', name='uq_extraction_job')
    )
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_jobs_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_jobs_status', ['status', 'lease_until'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status')
        batch_op.drop_index(batch_op.f('ix_extraction_jobs_run_id'))

    op.drop_table('extraction_jobs')
    # ### end Alembic commands ###
