"""stage jobs

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 13:49:05.033314
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.String(length=16), nullable=False, server_default='EXTRACT'))
        batch_op.add_column(sa.Column('metrics', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.drop_constraint(batch_op.f('uq_extraction_job'), type_='unique')
        batch_op.create_unique_constraint('uq_extraction_job', ['run_id', 'stage', 'partition_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_extraction_job', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_extraction_job'), ['run_id', 'partition_id'])
        batch_op.drop_column('metrics')
        batch_op.drop_column('stage')

    # ### end Alembic commands ###
