"""Honest capability matrix. `status` vocabulary:
  implemented-simulated : real logic, exercised by automated tests, but only against the synthetic SAP adapter
  designed              : documented design, no code
  catalogued            : data/catalog only, no execution engine
  planned               : not started
Nothing in this MVP is `production-ready against real SAP`.
"""

CAPABILITIES = [
    ("M1 Landscape discovery", "System registry, readiness, refresh-combination matrix", "implemented-simulated",
     "ECC 6.0 EHP8 and S/4HANA 2023 (both simulated)", "Static metadata; no RFC/ABAP agent", "tests/test_landscape.py", "RFC/OData adapter, DD02L/DD03L metadata, DB sizing"),
    ("M2 Full system refresh", "13-phase program executed end to end: pair/target guards, approved pre-copy profile, change-approver + Basis-lead approvals bound to a hash, verified pre-copy backup, quiesce, atomic copy via a mechanism adapter, post-copy through the factory (3 approvals), smoke tests, whole-target discovery-extended masking verified against pre-mask values, security gate + officer sign-off, release by an approver, exact rollback from backup, unmasked-target flag", "implemented-simulated",
     "ECC and S/4HANA homogeneous copy (simulated)", "Copy mechanism is an in-memory stand-in: SWPM, HANA backup/recovery and storage snapshots are NOT built; no maintenance windows, downtime estimates or real backup verification; masking runs over the simulated DDIC subset only", "tests/test_fullrefresh.py, tests/test_landscape.py::test_full_refresh_guard", "Real mechanism adapters (SWPM, HANA, snapshots), real backup verification, windows and notifications, durable orchestration, PRD hardware-key/licence handling"),
    ("M3 Post-copy factory", "17 executable tasks (jobs, mail, RFC, IDoc, schedulers, printers, monitoring, cloud, PI/PO + Integration Suite, gateway aliases, certificates/SSO, users, licence, TMS, instance parameters, BDLS logical systems, HANA checks), pre-copy target profile with approval, assessment, role-based approvals, per-task pre-check/action/post-check/rollback, retry/halt/resume, run rollback, independent verification gate, evidence package", "implemented-simulated",
     "ECC and S/4HANA (version-aware: S/4-only gateway aliases, SAP_BASIS minimum, HANA-only checks) against a SIMULATED technical configuration", "Acts on simulated technical state only: no RFC/SOAP/OData calls to SAP; BDLS is a count conversion, not the real report; user handling covers lock/role removal/password-reset flag, not USR02 or authorization internals; the system copy itself (runbook phase 7) is not executable", "tests/test_postcopy.py, tests/test_api.py::test_post_copy_factory_over_http, tests/test_governance.py", "Real adapters per task (SM59/SCOT/WE20/STRUST/STMS/BDLS via released APIs), per-release task variants, user-master integration, scheduler for post-copy on copy completion, link to the system-copy orchestrator"),
    ("M4 Lean client builder", "Approved reusable environment templates (training, sandbox, functional, regression), client shell, configuration-only baseline with dependency-driven customizing, masked master data, selective and synthetic transactional slices, lean-vs-full-client-copy estimate, 7 readiness checks incl. client-wide integrity and residual-PII scan, overwrite protection, retention/expiry, controlled rollback of failed builds, guarded decommission", "implemented-simulated",
     "ECC and S/4HANA (simulated clients in a host system)", "Does not call SAP client-copy programs (SCC4/SCCL/SCC9); user master and authorizations, client-independent customizing and repository are not modelled; synthetic slice sizes vary slightly from the estimate; duration is a placeholder model", "tests/test_lean.py, tests/test_api.py::test_lean_client_builder_over_http", "Real client creation and client-copy integration (RFC/ABAP agent), user and authorization handling, client-independent customizing checks, rebuild/refresh of an existing lean client, per-client cost and capacity planning"),
    ("M5 Selective data copy", "Manifest, scope filters, preview, volume estimate", "implemented-simulated",
     "ECC 6.0 EHP8 and S/4HANA 2023 subsets (27 tables incl. BUT000, ACDOCA)", "In-memory adapter; staging is local files", "tests/test_selective_flow.py", "ABAP extraction agent, object store staging, real loaders"),
    ("M6 Dependency engine", "Semantic graph, recursive expansion, cycles, orphans, dangling refs, extension API", "implemented-simulated",
     "SD/MM/FI/MD objects for ECC and S/4 (BP, ACDOCA); no PP/QM/PM/PS/WM, no S/4 MATDOC", "Relationships are hand-modelled", "tests/test_dependency.py", "More objects, learned relationships from DDIC/change docs"),
    ("M7 Masking", "Catalog + pattern discovery, FPE-style substitution, pseudonymize/anonymize/tokenize, coverage evidence", "implemented-simulated",
     "Field-level, SAP subset", "Not NIST FF1/FF3; no HSM/KMS", "tests/test_masking.py", "KMS/HSM, vetted FPE, payroll/HR objects, in-DB masking"),
    ("M8 Delta refresh", "Approved standing scenarios, multi-object rolling scopes, change-log/created-only/full-compare mechanisms, full sweeps, watermarks, target-drift detection, deferred/stale retry, resume/rollback, weekly/interval schedule with window and external-scheduler tick", "implemented-simulated",
     "ECC and S/4HANA (simulated change log)", "Change log is a simulation of CDHDR/CDPOS; no real change-document reader; target drift covers rows we loaded; source deletions reported, never propagated; scheduler is pull-based (tick), no built-in daemon", "tests/test_delta.py, tests/test_api.py::test_delta_refresh_over_http", "Real change-document readers per object class, durable scheduler, parallel packages, per-object mechanism profiles from metadata, S/4 MATDOC/ACDOCA delta specifics"),
    ("M9 TDM factory", "Scenario templates (O2C x3, intercompany-partial, P2P-to-PO, R2R billing postings, customer/vendor/material masters), catalog with discovery, self-service requests under an approved policy with quotas, subset and synthetic provisioning, exclusive reservations with TTL, golden datasets with verified restore, test-case association and usage, expiry sweep, guarded purge, CI/CD REST API", "implemented-simulated",
     "ECC and S/4HANA (Business Partner, ACDOCA)", "No make-to-stock/order, asset accounting, inventory/WM, goods/invoice receipt, intercompany billing (data model lacks PP, FI-AA, MM-IM); SAP Cloud ALM and test-management connectors NOT implemented (free-form test-case references only); synthetic data needs master data in the target first; no outbound webhooks", "tests/test_tdm.py, tests/test_api.py::test_test_data_catalog_over_http", "Cloud ALM/Jira/Xray connectors, more process templates (PP, FI-AA, MM-IM, intercompany), per-field synthetic distributions, webhook callbacks, persistent catalog, capacity planning"),
    ("M10 Conflict management", "Duplicate/identical/different, config gaps, number ranges, cascade, ownership, policies", "implemented-simulated",
     "Document and master objects", "REMAP not implemented; UPDATE only for master data", "tests/test_conflicts.py", "Remap, richer ownership model"),
    ("M11 Reconciliation", "Technical, business and security checks, release gate, evidence ZIP", "implemented-simulated",
     "SD/FI/MD checks", "Checks cover loaded scope only", "tests/test_selective_flow.py, test_reconcile.py, test_s4hana.py", "Inventory/open-item/valuation checks, PP/MM-IM"),
    ("M12 AI agents", "12 evidence-grounded agents (landscape, strategy, dependency, scope, masking, scheduling, conflicts, post-copy, reconciliation, performance, compliance, documentation); human-only accept/apply; hand-off-only destructive actions; keyword copilot; optional LLM narration", "implemented-simulated",
     "-", "Deterministic rules, no LLM decisions; narration (Anthropic API) is optional, off by default and untested against the live API; root-cause and performance hints are heuristics over simulated data", "tests/test_agents.py", "LLM planning agents under a policy engine; calibrated predictors; real-landscape evidence"),
    ("M13 Control tower UI", "React/TS control tower with 17 views (dashboard, landscape, readiness, selective designer, delta, dependencies, conflicts, masking, execution, reconciliation, lean client, full refresh, post-copy, orchestration, test catalog, audit, AI agents), role-aware controls, simulated-data banner, dark theme", "implemented-simulated",
     "-", "Not every planned screen exists; one theme (dark) only; automated accessibility checks cover WCAG 2.2 A/AA rules that tools can detect, a manual screen-reader and usability review has NOT been done; tested in Chromium only; no visual-regression tests", "frontend/e2e (Playwright: 9 journeys, axe scans of 17 views x 2 states, keyboard/landmark/tabs/reflow/contrast behaviour tests)", "Remaining screens, manual assistive-technology audit, Firefox/WebKit runs, visual regression, light theme"),
    ("M14 Orchestration", "Job queue with priorities, dependencies and pipelines (all-or-nothing creation, cycle check), human gates with escalation, idempotent submission, approved schedules (daily/weekly/interval; hash-bound, no double firing, missed occurrences recorded), maintenance windows per target (overnight wrap, blackouts), target leases (a full refresh holds its target), retry with backoff for transient errors only, dead-lettering, event feed and notification subscriptions, plus the checkpoint/retry/resume/rollback inside each run", "implemented-simulated",
     "-", "Jobs run one at a time (no parallel workers); in-memory queue (not durable); an external scheduler must call tick; notifications are recorded by a stand-in and never sent; the clock is movable for demonstration; leases cover orchestrated work only, not manual API calls", "tests/test_orchestration.py, tests/test_execution.py", "Durable workflow engine (Temporal/Argo), parallel workers with throttling, a clock-driven daemon, real e-mail/chat/webhook delivery, leases enforced inside every module"),
    ("M15 Security", "Roles with separation of duties and agent restrictions; OIDC-style bearer-token login (RS256/ES256 via JWKS, issuer/audience/expiry checks, key rotation, failed-login audit) alongside demo-header auth; attribute-based scoping by system and company code (selective manifests and plan dependency closure, delta, test-data requests, listings, agent reports); envelope-encrypted state with data-key and key-encryption-key rotation; HMAC-signed hash-chained audit log with a signed head for external escrow", "implemented-simulated",
     "-", "No browser login flow (a pasted token), no refresh or revocation (tokens are trusted until expiry), JWKS-by-URL untested against a real IdP; ABAC covers systems and company codes only (not plants, sales orgs or rows) and lean/post-copy/full refresh only by system; keys sit in files/environment (no KMS adapter built); the audit log is signed but not WORM storage, and truncation is only detectable against an escrowed head; single tenant", "tests/test_auth.py, tests/test_governance.py, tests/test_persistence.py, frontend/e2e/security.spec.ts", "Authorization Code + PKCE login, token revocation/introspection, KMS/HSM key providers, plant/org/row-level ABAC, tenant isolation, WORM/object-lock audit sink and SIEM export, real-IdP integration tests"),
    ("M16 Persistence", "Durable platform state: aggregates (systems with simulated adapters, projects with plans and masking engines, runs, delta/TDM/lean/post-copy/full-refresh state, agent reports, the orchestration queue, schedules, windows and leases) stored by change in one SQLite transaction per mutating request; restored on start; encrypted and authenticated at rest (Fernet), allow-listed unpickling, refusal on wrong key/tampering/schema mismatch, interrupted work reported", "implemented-simulated",
     "-", "SQLite, not PostgreSQL; one writer (mutating requests are serialised); saves at request boundaries so a crash loses the in-flight request whole while the audit log still shows the attempt; no migrations, online backup or version history; the key file sits next to the database unless RFACTORY_STATE_KEY is set (no KMS); pickle-based, so tied to this code version", "tests/test_persistence.py, frontend/e2e/durability.spec.ts", "PostgreSQL repositories (db/schema.sql), migrations, KMS/HSM key custody, backup/restore and retention, multi-writer concurrency"),
]
