import { useEffect, useState } from "react";
import { api, sessionInfo } from "../api";
import { useApi, useProjectDetails } from "../hooks";
import { Banner, Card, ErrorBox, Pill, Pre, Segmented, Select, Table, Tabs } from "../components/ui";
import { LookupPanel, RuleDoc, RuleGrid } from "../components/RuleGrid";

const EMPTY: RuleDoc = { ruleset: "", description: "", lookups: {}, rules: [], tests: [] };

export default function RulesWorkbench() {
  const { projectId, source } = useProjectDetails();
  const manifests = useApi<any[]>(projectId ? `/projects/${projectId}/manifests` : null);
  const rulesets = useApi<any[]>(projectId ? `/projects/${projectId}/rulesets` : null);
  const roles: string[] = sessionInfo()?.user?.roles || [];
  const canDecide = roles.includes("approver") || roles.includes("admin");
  const canEdit = roles.includes("architect") || roles.includes("admin");
  const [mid, setMid] = useState("");
  const [rid, setRid] = useState("");
  const [grid, setGrid] = useState<any>(null);
  const [doc, setDoc] = useState<RuleDoc>(EMPTY);
  const [dirty, setDirty] = useState(false);
  const [mode, setMode] = useState("grid");
  const [yaml, setYaml] = useState("");
  const [val, setVal] = useState<any>(null);
  const [dry, setDry] = useState<any>(null);
  const [err, setErr] = useState<string | null>(null);
  const [msg, setMsg] = useState<string | null>(null);
  const [bukrs, setBukrs] = useState("5000");
  const [learn, setLearn] = useState(false);
  const [learning, setLearning] = useState<any>(null);
  const guard = async (fn: () => Promise<void>) => { setErr(null); setMsg(null); try { await fn(); } catch (e: any) { setErr(e.message); } };
  const load = (id: string) => guard(async () => { setRid(id); const g = await api(`/rulesets/${id}/rules`); setGrid(g); setDoc(g.document); setDirty(false); const r = await api(`/rulesets/${id}`); setYaml(r.source_yaml); setVal(r.validation); setDry(null); });
  useEffect(() => { if (!rid && rulesets.data?.length) load(rulesets.data[0].id); }, [rulesets.data]);
  const edit = (d: RuleDoc) => { setDoc(d); setDirty(true); };
  const generate = () => guard(async () => { const r = await api(`/projects/${projectId}/rulesets/generate`, { method: "POST", params: { manifest_id: mid || manifests.data?.[0]?.id, learn: learn || undefined } }); const c = await api(`/projects/${projectId}/rulesets/compose`, { body: { source_yaml: r.source_yaml } }); setYaml(r.source_yaml); setDoc(c.document); setVal(c.validation); setDirty(true); setLearning(r.learning || null); setMsg(r.learning ? `Candidate rules generated; ${r.learning.proposed.length} learned rule(s) from ${r.learning.approved_rulesets} approved rule set(s) of other projects (provenance in each rule's description). Review them in the grid, then save as a new version.` : "Candidate rules generated by the Rule Factory: review them in the grid, then save as a new version."); });
  const validate = () => guard(async () => { const c = await api(`/projects/${projectId}/rulesets/compose`, { body: mode === "yaml" ? { source_yaml: yaml } : { document: doc } }); setVal(c.validation); if (c.source_yaml) { setYaml(c.source_yaml); if (mode === "yaml") { setDoc(c.document); } } });
  const applyYaml = () => guard(async () => { const c = await api(`/projects/${projectId}/rulesets/compose`, { body: { source_yaml: yaml } }); setVal(c.validation); if (!c.document) throw new Error(c.validation.errors.join("; ")); setDoc(c.document); setDirty(true); setMode("grid"); });
  const save = () => guard(async () => { const body = mode === "yaml" ? { source_yaml: yaml, based_on: rid || undefined } : { document: doc, based_on: rid || undefined }; const r = await api(`/projects/${projectId}/rulesets`, { body }); rulesets.reload(); await load(r.id); setMsg(`Saved ${r.name} v${r.version}${r.decisions.approved ? ` · ${r.decisions.approved} decision(s) carried over for unchanged rules` : ""}.`); });
  const dryRun = () => guard(async () => setDry(await api(`/rulesets/${rid}/dry-run`, { body: { system_id: source.id, bukrs, tables: ["BKPF", "BSEG", "KNA1", "KNB1", "LFA1", "VBAK", "EKKO", "MARC", "CSKS"], sample_size: 40 } })));
  const approve = () => guard(async () => { await api(`/rulesets/${rid}/approve`, { body: {} }); rulesets.reload(); await load(rid); setMsg("Rule set approved; every rule still pending was approved with it."); });
  const decide = (ruleId: string, decision: "APPROVED" | "REJECTED" | "PENDING") => guard(async () => {
    let comment = "";
    if (decision === "REJECTED") { comment = window.prompt(`Why is rule ${ruleId} rejected? (recorded in the audit trail)`) || ""; if (!comment) return; }
    await api(`/rulesets/${rid}/rules/${ruleId}/decision`, { body: { decision, comment } });
    setGrid(await api(`/rulesets/${rid}/rules`)); rulesets.reload();
  });
  const parseCsv = (name: string, text: string, keyColumn: string, valueColumn: string) => api("/rulesets/lookups/from-csv", { body: { name, text, key_column: keyColumn || null, value_column: valueColumn || null } });
  if (!projectId || !source) return <Banner>Select a project.</Banner>;
  const current = (rulesets.data || []).find((r) => r.id === rid);
  const saved: Record<string, any> = Object.fromEntries((grid?.rules || []).map((r: any) => [r.id, r]));
  const dec = grid?.decisions;
  const lines = (which: "before" | "after") => Object.entries(dry?.tables || {}).flatMap(([t, d]: any) => d.samples.slice(0, 4).map((smp: any) => { const r = smp[which] || {}; return `${t} ${["BUKRS", "BELNR", "HKONT", "KUNNR", "LIFNR", "MATNR", "WERKS", "DMBTR"].filter((k) => r[k] !== undefined).map((k) => r[k]).join(" ")}`; }));
  const editable = canEdit; // edits never touch a saved version: they are saved as the next one
  return (
    <div>
      <Card title={dirty ? "Rules (unsaved changes)" : "Rules of the current set"} actions={<>
        <Select value={rid} onChange={load} options={(rulesets.data || []).map((r) => ({ value: r.id, label: `${r.name} v${r.version} · ${r.status}` }))} placeholder="rule set" />
        {current && <Pill value={dirty ? "EDITED" : current.status} />}
        {dec && !dirty && <span className="muted">{dec.approved} approved · {dec.rejected} rejected · {dec.pending} pending</span>}
      </>}>
        <RuleGrid doc={doc} saved={dirty ? {} : saved} impact={dry?.rule_impact || {}} canDecide={canDecide && !dirty && !!current && current.status === "DRAFT"} editable={editable} onChange={edit} onDecide={decide} />
        <div className="row" style={{ marginTop: 14 }}>
          <button disabled={!doc.rules.length || !canEdit} onClick={save}>{rid ? "Save as new version" : "Save rule set"}</button>
          <button className="secondary" disabled={!doc.rules.length} onClick={validate}>Validate + run embedded tests</button>
          <button className="secondary" disabled={!rid || dirty} onClick={dryRun}>Dry-run on the source sample</button><input value={bukrs} onChange={(e) => setBukrs(e.target.value)} style={{ width: 110 }} placeholder="company code" />
          <button className="secondary" disabled={!current || dirty || current.status !== "DRAFT" || !current.validation?.ok || !!dec?.rejected} onClick={approve}>Approve rule set (four-eyes)</button>
        </div>
        {!!dec?.rejected && !dirty && <p className="note-danger">{dec.rejected} rule(s) rejected by an approver: remove or rework them and save a new version; the set cannot be approved while they remain.</p>}
        {dirty && <p className="muted">Edits apply to a new version when saved; decisions of unchanged rules carry over. Approving rules is done on the saved version.</p>}
        {!rid && !doc.rules.length && <p className="note-danger">No rule set yet: generate candidate rules from a manifest, add rules or paste YAML, then save.</p>}
        <ErrorBox error={err} />
        {msg && <Banner>{msg}</Banner>}
        {val && <div style={{ marginTop: 10 }}><Pill value={val.ok ? "VALID" : "INVALID"} /> {val.rule_count} rules · tests {val.tests.passed} passed / {val.tests.failed} failed{val.errors.map((e: string) => <div key={e} className="banner danger">{e}</div>)}{val.warnings.map((w: string) => <div key={w} className="banner warn">{w}</div>)}</div>}
        {dry && <div className="grid2" style={{ marginTop: 12 }}><Card title="Source lines"><Pre value={lines("before").join("\n")} /></Card><Card title="Preview"><Pre value={lines("after").join("\n")} /></Card></div>}
        {dry && <p className="muted">{dry.records} records sampled · {dry.changed} changed · {dry.exceptions.length} exceptions. Amounts are never rewritten by organisational rules; the full lineage is under Dry run &amp; impact.</p>}
      </Card>
      <Card title="Rule editor" actions={<><Segmented value={mode} onChange={setMode} options={[{ value: "grid", label: "Grid" }, { value: "yaml", label: "YAML" }]} /><Select value={mid} onChange={setMid} options={(manifests.data || []).map((m) => ({ value: m.id, label: `${m.name} v${m.version}` }))} placeholder="manifest for generation" /><label className="chk" title="mappings the approved rule sets of other projects agree on are proposed as learned rules with their provenance; conflicts are listed, organisational fields are never learned"><input type="checkbox" checked={learn} onChange={(e) => setLearn(e.target.checked)} /> learn from approved rule sets</label><button className="secondary" disabled={!canEdit} onClick={generate}>Generate candidate rules (Rule Factory)</button></>}>
        {learning && <div className="banner info" style={{ marginBottom: 10 }}>Learned from {learning.approved_rulesets} approved rule set(s): {learning.proposed.length ? learning.proposed.join(", ") : "nothing new to propose"}{learning.review?.length ? ` · for review: ${learning.review.join(" · ")}` : ""}</div>}
        {mode === "grid" ? <div className="rc-form">
          <div className="row"><label>Rule set name<input value={doc.ruleset} onChange={(e) => edit({ ...doc, ruleset: e.target.value })} placeholder="spinco-5000-rules" /></label><label>Description<input value={doc.description || ""} onChange={(e) => edit({ ...doc, description: e.target.value })} /></label></div>
          <p className="muted">Edit rules in the grid above (Edit, reorder, Remove, Add rule). Lookup tables used by the rules:</p>
          <LookupPanel doc={doc} onChange={edit} parseCsv={parseCsv} />
        </div> : <>
          <textarea className="code" value={yaml} onChange={(e) => setYaml(e.target.value)} placeholder="ruleset: my-rules&#10;rules:&#10;  - id: cc&#10;    type: org_reassign&#10;    field: BUKRS&#10;    map: {'5000': 'SP01'}" />
          <div className="row" style={{ marginTop: 8 }}><button className="secondary" disabled={!yaml} onClick={applyYaml}>Apply YAML to the grid</button><span className="muted">The YAML is the DSL that is hashed and approved; the grid is its editor.</span></div>
        </>}
      </Card>
      <Tabs tabs={[
        { id: "rs", label: "Rule sets", content: <Card><Table cols={[{ k: "name", h: "Name", r: (r) => <a href="#" onClick={(e) => { e.preventDefault(); load(r.id); }}>{r.name}</a> }, { k: "version", h: "v" }, { k: "status", h: "Status", r: (r) => <Pill value={r.status} /> }, { k: "rule_count", h: "Rules" }, { k: "d", h: "Decisions", r: (r) => `${r.decisions?.approved ?? 0} / ${r.decisions?.rejected ?? 0} / ${r.decisions?.pending ?? 0}` }, { k: "v", h: "Valid", r: (r) => <Pill value={r.validation?.ok ? "VALID" : "INVALID"} /> }, { k: "content_hash", h: "Hash", r: (r) => r.content_hash.slice(0, 12) }, { k: "created_by", h: "Created by" }, { k: "approved_by", h: "Approved by" }]} rows={rulesets.data || []} /><p className="muted">Decisions: approved / rejected / pending per rule.</p></Card> },
        { id: "dry", label: "Dry run & impact", content: <Card actions={<><input value={bukrs} onChange={(e) => setBukrs(e.target.value)} style={{ width: 90 }} /><button disabled={!rid} onClick={dryRun}>Dry run on source sample</button></>}>{dry && <><p>{dry.records} records sampled · {dry.changed} changed · {dry.exceptions.length} exceptions</p><div className="grid2"><div><h4>Impact per rule</h4><Table cols={[{ k: "rule", h: "Rule" }, { k: "n", h: "Field changes" }]} rows={Object.entries(dry.rule_impact).map(([rule, n]) => ({ rule, n }))} /><h4>Exceptions</h4><Table cols={[{ k: "table", h: "Table" }, { k: "key", h: "Key" }, { k: "rule", h: "Rule" }, { k: "message", h: "Message" }]} rows={dry.exceptions} /></div><div><h4>Before / after samples</h4>{Object.entries(dry.tables).map(([t, d]: any) => d.samples.slice(0, 2).map((s: any, i: number) => <div key={t + i}><b>{t}</b> lineage: {s.lineage.map((l: any) => `${l.rule}: ${l.field} ${l.from}→${l.to}`).join("; ")}<Pre value={{ before: s.before, after: s.after }} /></div>))}</div></div></>}</Card> },
      ]} />
    </div>
  );
}
